language: node_js
node_js:
- 12.13.0
install:
- npm install
script:
- npm run lint
- bash test/versionCheck.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
- npm test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    branch: master
